package vip.epss.domain;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uiid
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    private Integer uiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.fuid
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    private Integer fuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uiid
     *
     * @return the value of userinfo.uiid
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public Integer getUiid() {
        return uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uiid
     *
     * @param uiid the value for userinfo.uiid
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public void setUiid(Integer uiid) {
        this.uiid = uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.fuid
     *
     * @return the value of userinfo.fuid
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public Integer getFuid() {
        return fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.fuid
     *
     * @param fuid the value for userinfo.fuid
     *
     * @mbg.generated Tue Oct 13 09:21:38 CST 2020
     */
    public void setFuid(Integer fuid) {
        this.fuid = fuid;
    }
}